### ISSUE TITLE
Responsiveness for XL Screens Not Displaying

### ISSUE THREAD

**Issue by Innkeeping** [MetaFam/dAcademy#37]
Carousel responsiveness is not showing on XL screen size

**Comment by Innkeeping** [comment]
@dysbulic has this been resolved with the new build?  Can you confirm on your XL screen?

**Comment by Innkeeping** [comment]
Book titles are not displaying properly on XL screens. @dysbulic

**Comment by dysbulic** [comment]
It was a Firefox issue because the container for the cover images is an anchor tag which is an inline element.

It has been resolved.
